package javac;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.kevinolarte.ejr.*;
import com.kevinolarte.ejr.tema07.ejr03.Ejr03;
import com.kevinolarte.ejr.tema07.ejr06.MainEjer06;
import com.kevinolarte.lib.Comprobate;

import net.datafaker.providers.entertainment.NewGirl;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        MainEjer06 E = new MainEjer06();
        
    }
}
