package javac;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.kevinolarte.ejr.*;
import com.kevinolarte.ejr.tema07.ejr03.Ejr03;
import com.kevinolarte.lib.Comprobate;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Ejr03 e = new Ejr03();
        
    }
}
